import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Search, ShieldPlus, Trash2 } from "lucide-react";
import { DmcaAccessDenied, DmcaError, DmcaLoading, DmcaPage } from "@/components/admin/dmca/support-page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { DMCA_PERMISSION_LABELS, DmcaPerm, dmcaFetch, useDmcaMe } from "@/lib/dmca-admin";

type GrantUser = { id: string; username: string; fullName?: string; role: string; permissions: string[] };
type SearchUser = { id: string; username: string; fullName?: string; role?: string };

export default function DmcaPermissionsPage() {
  const me = useDmcaMe(); const qc = useQueryClient();
  const [addOpen, setAddOpen] = useState(false); const [q, setQ] = useState(""); const [selected, setSelected] = useState<SearchUser | null>(null);
  const [mode, setMode] = useState("dmca_admin"); const [individual, setIndividual] = useState<string[]>([]);
  const [revokeUser, setRevokeUser] = useState<GrantUser | null>(null); const [revokePermissions, setRevokePermissions] = useState<string[]>([]);
  const query = useQuery<{ users: GrantUser[] }>({ queryKey: ["/api/admin/dmca/permissions"], queryFn: () => dmcaFetch("/permissions"), enabled: me.can(DmcaPerm.MANAGE_PERMISSIONS), placeholderData: undefined });
  const search = useQuery<SearchUser[]>({ queryKey: ["/api/admin/dmca/permissions/search", q], queryFn: async () => { const v = await dmcaFetch<any>(`/permissions/search?q=${encodeURIComponent(q)}`); return Array.isArray(v) ? v : Array.isArray(v?.users) ? v.users : []; }, enabled: me.can(DmcaPerm.MANAGE_PERMISSIONS) && q.trim().length >= 2, placeholderData: undefined });
  const refresh = () => qc.invalidateQueries({ queryKey: ["/api/admin/dmca/permissions"] });
  const grant = useMutation({ mutationFn: () => dmcaFetch(`/permissions/${selected!.id}/grant`, { method: "POST", body: mode === "individual" ? { permissions: individual } : { bundle: mode } }), onSuccess: () => { setAddOpen(false); setSelected(null); setQ(""); setIndividual([]); refresh(); } });
  const revoke = useMutation({ mutationFn: () => dmcaFetch(`/permissions/${revokeUser!.id}/revoke`, { method: "POST", body: { permissions: revokePermissions } }), onSuccess: () => { setRevokeUser(null); setRevokePermissions([]); refresh(); } });
  if (me.isLoading) return <DmcaPage title="DMCA permissions" description="Manage legal-compliance access."><DmcaLoading /></DmcaPage>;
  if (!me.can(DmcaPerm.MANAGE_PERMISSIONS)) return <DmcaAccessDenied />;
  const users = !query.isPlaceholderData && Array.isArray(query.data?.users) ? query.data!.users : [];
  const bundles = me.data?.bundles || { moderator: [], dmca_admin: [], legal_admin: [] }; const allPermissions = Array.isArray(me.data?.allPermissions) ? me.data!.allPermissions : [];
  const toggle = (p: string, list: string[], set: (v: string[]) => void) => set(list.includes(p) ? list.filter((x) => x !== p) : [...list, p]);
  return <DmcaPage title="DMCA permissions" description="Grant and revoke scoped DMCA permissions. Site roles do not implicitly grant DMCA access.">
    <div className="flex justify-end"><Button onClick={() => setAddOpen(true)} data-testid="button-add-dmca-user"><ShieldPlus className="mr-2 h-4 w-4" />Add user / grant access</Button></div>
    {query.isLoading ? <DmcaLoading /> : query.error ? <DmcaError error={query.error} /> : <Card><CardContent className="pt-6"><Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead>Site role</TableHead><TableHead>DMCA grants</TableHead><TableHead /></TableRow></TableHeader><TableBody>{users.map((u) => <TableRow key={u.id} data-testid={`row-permission-user-${u.id}`}><TableCell><strong>{u.fullName || u.username}</strong><div className="text-xs text-muted-foreground">@{u.username}</div></TableCell><TableCell>{u.role}</TableCell><TableCell className="space-x-1">{u.permissions.map((p) => <Badge key={p} variant="secondary" title={DMCA_PERMISSION_LABELS[p]}>{p}</Badge>)}</TableCell><TableCell><Button variant="outline" size="sm" disabled={!u.permissions.length} onClick={() => { setRevokeUser(u); setRevokePermissions([...u.permissions]); }} data-testid={`button-revoke-user-${u.id}`}><Trash2 className="mr-2 h-4 w-4" />Revoke</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
    <Dialog open={addOpen} onOpenChange={setAddOpen}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Grant DMCA access</DialogTitle><DialogDescription>Search for a user, then grant a standard bundle or specific permissions.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>User search</Label><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={q} onChange={(e) => { setQ(e.target.value); setSelected(null); }} data-testid="input-permission-user-search" /></div>{selected && <p className="mt-2 text-sm">Selected: {selected.fullName || selected.username} (@{selected.username})</p>}{Array.isArray(search.data) && !selected && search.data.map((u) => <Button key={u.id} variant="ghost" className="w-full justify-start" onClick={() => setSelected(u)} data-testid={`button-select-permission-user-${u.id}`}>{u.fullName || u.username} (@{u.username})</Button>)}</div><div><Label>Grant type</Label><Select value={mode} onValueChange={setMode}><SelectTrigger data-testid="select-grant-type"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="moderator">Moderator</SelectItem><SelectItem value="dmca_admin">DMCA Admin</SelectItem><SelectItem value="legal_admin">Legal Admin</SelectItem><SelectItem value="individual">Individual permissions</SelectItem></SelectContent></Select></div>{mode !== "individual" ? <div className="rounded border p-3"><p className="mb-2 font-medium">{mode.replace("_", " ")} includes:</p><div className="flex flex-wrap gap-1">{(bundles[mode as keyof typeof bundles] || []).map((p) => <Badge key={p} variant="outline">{DMCA_PERMISSION_LABELS[p] || p}</Badge>)}</div></div> : <div className="grid gap-2">{allPermissions.map((p) => <label key={p} className="flex items-start gap-2 rounded border p-2"><Checkbox checked={individual.includes(p)} onCheckedChange={() => toggle(p, individual, setIndividual)} data-testid={`checkbox-grant-${p}`} /><span><strong>{p}</strong><br /><span className="text-sm text-muted-foreground">{DMCA_PERMISSION_LABELS[p]}</span></span></label>)}</div>}{grant.error && <DmcaError error={grant.error} />}</div><DialogFooter><Button variant="outline" onClick={() => setAddOpen(false)} data-testid="button-cancel-grant">Cancel</Button><Button disabled={!selected || (mode === "individual" && !individual.length) || grant.isPending} onClick={() => grant.mutate()} data-testid="button-confirm-grant">Grant access</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!revokeUser} onOpenChange={(o) => !o && setRevokeUser(null)}><DialogContent><DialogHeader><DialogTitle>Revoke DMCA permissions?</DialogTitle><DialogDescription>Select grants to revoke from @{revokeUser?.username}. The last holder of dmca.manage_permissions cannot be removed.</DialogDescription></DialogHeader><div className="space-y-2">{revokeUser?.permissions.map((p) => <label key={p} className="flex gap-2 rounded border p-2"><Checkbox checked={revokePermissions.includes(p)} onCheckedChange={() => toggle(p, revokePermissions, setRevokePermissions)} data-testid={`checkbox-revoke-${p}`} />{DMCA_PERMISSION_LABELS[p] || p}</label>)}{revoke.error && <DmcaError error={revoke.error} />}</div><DialogFooter><Button variant="outline" onClick={() => setRevokeUser(null)} data-testid="button-cancel-revoke">Cancel</Button><Button variant="destructive" disabled={!revokePermissions.length || revoke.isPending} onClick={() => revoke.mutate()} data-testid="button-confirm-revoke">Confirm revoke</Button></DialogFooter></DialogContent></Dialog>
  </DmcaPage>;
}