import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronDown, ChevronRight, Gavel } from "lucide-react";
import { DmcaAccessDenied, DmcaError, DmcaLoading, DmcaPage } from "@/components/admin/dmca/support-page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { DmcaPerm, dmcaFetch, useDmcaMe } from "@/lib/dmca-admin";

type Event = { id: string; caseNumber?: string; eventType: string; eventDate: string; notes?: string; countsTowardRepeatPolicy?: boolean };
type User = { id: string; username: string; fullName?: string; email: string; isBlocked: boolean; activeStrikes: number; totalEvents: number; lastEventAt: string; overThreshold: boolean; inReview: boolean; reviewOpenedAt: string | null; lastDecision?: { eventType: string; eventDate: string; notes?: string } | null; events: Event[] };
type Data = { threshold: number; windowMonths: number; users: User[] };

export default function RepeatInfringersPage() {
  const me = useDmcaMe(); const qc = useQueryClient();
  const [expanded, setExpanded] = useState<Set<string>>(new Set()); const [selected, setSelected] = useState<User | null>(null);
  const [decision, setDecision] = useState("warning"); const [notes, setNotes] = useState(""); const [terminateConfirmed, setTerminateConfirmed] = useState(false);
  const query = useQuery<Data>({ queryKey: ["/api/admin/dmca/repeat-infringers"], queryFn: () => dmcaFetch("/repeat-infringers"), enabled: me.can(DmcaPerm.MANAGE_REPEAT_INFRINGER), placeholderData: undefined });
  const mutation = useMutation({ mutationFn: () => dmcaFetch(`/repeat-infringers/${selected!.id}/decision`, { method: "POST", body: { decision, notes } }), onSuccess: () => { setSelected(null); setNotes(""); setTerminateConfirmed(false); qc.invalidateQueries({ queryKey: ["/api/admin/dmca/repeat-infringers"] }); } });
  if (me.isLoading) return <DmcaPage title="Repeat-infringer review" description="Human review of copyright event history."><DmcaLoading /></DmcaPage>;
  if (!me.can(DmcaPerm.MANAGE_REPEAT_INFRINGER)) return <DmcaAccessDenied />;
  const data = !query.isPlaceholderData && query.data && Array.isArray(query.data.users) ? query.data : null;
  return <DmcaPage title="Repeat-infringer review" description="Review strikes and make explicit, documented account decisions. Decisions are never automatic.">
    {query.isLoading ? <DmcaLoading /> : query.error ? <DmcaError error={query.error} /> : <><Card><CardContent className="pt-6"><p className="mb-4 text-sm text-muted-foreground">Policy threshold: <strong>{data?.threshold}</strong> counting events in <strong>{data?.windowMonths} months</strong>. Meeting the threshold triggers review only—not an automatic penalty.</p><Table><TableHeader><TableRow><TableHead /><TableHead>User</TableHead><TableHead>Strikes</TableHead><TableHead>Total events</TableHead><TableHead>Status</TableHead><TableHead>Last decision</TableHead><TableHead /></TableRow></TableHeader><TableBody>{(data?.users || []).map((u) => <><TableRow key={u.id} className={u.overThreshold ? "bg-amber-50 dark:bg-amber-950/20" : ""} data-testid={`row-repeat-user-${u.id}`}><TableCell><Button variant="ghost" size="icon" onClick={() => setExpanded((old) => { const n = new Set(old); n.has(u.id) ? n.delete(u.id) : n.add(u.id); return n; })} data-testid={`button-expand-events-${u.id}`}>{expanded.has(u.id) ? <ChevronDown /> : <ChevronRight />}</Button></TableCell><TableCell><strong>{u.fullName || u.username}</strong><div className="text-xs text-muted-foreground">@{u.username} · {u.email}</div></TableCell><TableCell><Badge variant={u.overThreshold ? "destructive" : "secondary"}>{u.activeStrikes} / {data?.threshold}</Badge></TableCell><TableCell>{u.totalEvents}</TableCell><TableCell>{u.isBlocked ? "Disabled" : u.inReview ? <Badge className="bg-amber-600 text-white" data-testid={`badge-in-review-${u.id}`}>In review{u.reviewOpenedAt ? ` since ${new Date(u.reviewOpenedAt).toLocaleDateString()}` : ""}</Badge> : u.overThreshold ? "Review required" : "Active"}</TableCell><TableCell>{u.lastDecision ? `${u.lastDecision.eventType} — ${new Date(u.lastDecision.eventDate).toLocaleDateString()}` : "None"}</TableCell><TableCell><Button size="sm" onClick={() => setSelected(u)} data-testid={`button-decision-${u.id}`}><Gavel className="mr-2 h-4 w-4" />Decision</Button></TableCell></TableRow>{expanded.has(u.id) && <TableRow key={`${u.id}-events`}><TableCell colSpan={7}><div className="ml-10 space-y-2">{(u.events || []).map((e) => <div key={e.id} className="rounded border p-3 text-sm" data-testid={`event-${e.id}`}><strong>{e.eventType}</strong> · {new Date(e.eventDate).toLocaleString()} {e.caseNumber && `· Case ${e.caseNumber}`}<div className="text-muted-foreground">{e.countsTowardRepeatPolicy ? "Counts toward policy" : "Does not count"}{e.notes ? ` — ${e.notes}` : ""}</div></div>)}</div></TableCell></TableRow>}</>)}</TableBody></Table></CardContent></Card></>}
    <Dialog open={!!selected} onOpenChange={(o) => !o && setSelected(null)}><DialogContent><DialogHeader><DialogTitle>Record human decision</DialogTitle><DialogDescription>This is always a human decision after review. The threshold never triggers automatic action.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Decision</Label><Select value={decision} onValueChange={(v) => { setDecision(v); setTerminateConfirmed(false); }}><SelectTrigger data-testid="select-repeat-decision"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="warning">Warning</SelectItem><SelectItem value="dismiss">Dismiss</SelectItem><SelectItem value="suspend">Suspend</SelectItem><SelectItem value="terminate">Terminate</SelectItem></SelectContent></Select></div><div><Label>Decision notes (required)</Label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} data-testid="input-decision-notes" /></div>{decision === "terminate" && <div className="rounded-md border border-destructive/40 bg-destructive/5 p-3 text-sm"><strong>Termination confirmation:</strong> The account will be disabled, not deleted. It and its records are preserved as evidence.<label className="mt-3 flex gap-2"><input type="checkbox" checked={terminateConfirmed} onChange={(e) => setTerminateConfirmed(e.target.checked)} data-testid="checkbox-confirm-termination" />I understand and confirm termination.</label></div>}{mutation.error && <DmcaError error={mutation.error} />}</div><DialogFooter><Button variant="outline" onClick={() => setSelected(null)} data-testid="button-cancel-decision">Cancel</Button><Button variant={decision === "terminate" ? "destructive" : "default"} disabled={!notes.trim() || (decision === "terminate" && !terminateConfirmed) || mutation.isPending} onClick={() => mutation.mutate()} data-testid="button-confirm-decision">Record decision</Button></DialogFooter></DialogContent></Dialog>
  </DmcaPage>;
}