import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, Save } from "lucide-react";
import { DmcaAccessDenied, DmcaError, DmcaLoading, DmcaPage } from "@/components/admin/dmca/support-page";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { DmcaApiError, DmcaPerm, dmcaFetch, useDmcaMe } from "@/lib/dmca-admin";

type Section = { key: string; title: string; body: string; pendingCounselReview: boolean };
type Settings = { agent: { name: string; organization: string; address: string; phone: string; email: string }; registrationNumber: string; registrationExpiresAt: string | null; repeatInfringerThreshold: number; repeatInfringerWindowMonths: number; reminderOffsets: { restoreReminderBusinessDay: number; restoreEligibleBusinessDay: number; restoreEscalationBusinessDay: number; restoreDeadlineBusinessDay: number; untouchedNoticeHours: number; agentRenewalReminderDays: number[] }; policySections: Section[] };

export default function DmcaSettingsPage() {
  const me = useDmcaMe(); const qc = useQueryClient();
  const query = useQuery<Settings>({ queryKey: ["/api/admin/dmca/settings"], queryFn: () => dmcaFetch("/settings"), enabled: me.can(DmcaPerm.MANAGE_PERMISSIONS), placeholderData: undefined });
  const form = useForm<Settings>({ defaultValues: { agent: { name: "", organization: "", address: "", phone: "", email: "" }, registrationNumber: "", registrationExpiresAt: "", repeatInfringerThreshold: 3, repeatInfringerWindowMonths: 36, reminderOffsets: { restoreReminderBusinessDay: 8, restoreEligibleBusinessDay: 10, restoreEscalationBusinessDay: 12, restoreDeadlineBusinessDay: 14, untouchedNoticeHours: 48, agentRenewalReminderDays: [90,30,7] }, policySections: [] } });
  useEffect(() => { if (!query.isPlaceholderData && query.data?.agent && Array.isArray(query.data.policySections)) form.reset({ ...query.data, registrationExpiresAt: query.data.registrationExpiresAt?.slice(0, 10) || "" }); }, [query.data, query.isPlaceholderData, form]);
  const save = useMutation({ mutationFn: (v: Settings) => dmcaFetch<Settings>("/settings", { method: "PUT", body: v }), onSuccess: (v) => { form.reset(v); qc.setQueryData(["/api/admin/dmca/settings"], v); }, onError: (e) => { if (e instanceof DmcaApiError) Object.entries(e.errors).forEach(([name, message]) => form.setError(name as any, { message })); } });
  if (me.isLoading) return <DmcaPage title="DMCA settings" description="Legal policy configuration."><DmcaLoading /></DmcaPage>;
  if (!me.can(DmcaPerm.MANAGE_PERMISSIONS)) return <DmcaAccessDenied />;
  if (query.isLoading) return <DmcaPage title="DMCA settings" description="Legal policy configuration."><DmcaLoading /></DmcaPage>;
  const expiry = form.watch("registrationExpiresAt"); const days = expiry ? Math.ceil((new Date(expiry).getTime() - Date.now()) / 86400000) : null;
  return <DmcaPage title="DMCA settings" description="Maintain designated-agent registration, public policy, deadlines, and repeat-infringer review thresholds.">{query.error && <DmcaError error={query.error} />}<Form {...form}><form className="space-y-6" onSubmit={form.handleSubmit((v) => save.mutate(v))}>
    <Card><CardHeader><CardTitle>Designated agent</CardTitle><CardDescription>Public Copyright Office contact details.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{(["name","organization","address","phone","email"] as const).map((name) => <FormField key={name} control={form.control} name={`agent.${name}`} render={({ field }) => <FormItem className={name === "address" ? "md:col-span-2" : ""}><FormLabel className="capitalize">{name}</FormLabel><FormControl>{name === "address" ? <Textarea {...field} data-testid={`input-agent-${name}`} /> : <Input {...field} type={name === "email" ? "email" : "text"} data-testid={`input-agent-${name}`} />}</FormControl><FormMessage /></FormItem>} />)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Copyright Office registration</CardTitle></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><FormField control={form.control} name="registrationNumber" render={({ field }) => <FormItem><FormLabel>Registration number</FormLabel><FormControl><Input {...field} data-testid="input-registration-number" /></FormControl><FormMessage /></FormItem>} /><FormField control={form.control} name="registrationExpiresAt" render={({ field }) => <FormItem><FormLabel>Expiry date</FormLabel><FormControl><Input {...field} value={field.value || ""} type="date" data-testid="input-registration-expiry" /></FormControl><FormMessage /></FormItem>} />{days !== null && days <= 60 && <div className={`md:col-span-2 flex gap-2 rounded p-3 ${days < 0 ? "bg-destructive/10 text-destructive" : "bg-amber-50 text-amber-900"}`} data-testid="status-registration-expiry"><AlertTriangle className="h-4 w-4" />{days < 0 ? `Registration expired ${Math.abs(days)} days ago.` : `Registration expires in ${days} days.`}</div>}</CardContent></Card>
    <Card><CardHeader><CardTitle>Repeat-infringer policy</CardTitle><CardDescription>Thresholds trigger human review only; account decisions are never automatic.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><FormField control={form.control} name="repeatInfringerThreshold" render={({ field }) => <FormItem><FormLabel>Counting-event threshold</FormLabel><FormControl><Input type="number" min={1} {...field} onChange={(e) => field.onChange(Number(e.target.value))} data-testid="input-repeat-threshold" /></FormControl><FormMessage /></FormItem>} /><FormField control={form.control} name="repeatInfringerWindowMonths" render={({ field }) => <FormItem><FormLabel>Window (months)</FormLabel><FormControl><Input type="number" min={1} {...field} onChange={(e) => field.onChange(Number(e.target.value))} data-testid="input-repeat-window" /></FormControl><FormMessage /></FormItem>} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Reminder offsets</CardTitle><CardDescription>Business-day restoration workflow and compliance reminders.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">{(["restoreReminderBusinessDay","restoreEligibleBusinessDay","restoreEscalationBusinessDay","restoreDeadlineBusinessDay","untouchedNoticeHours"] as const).map((name) => <FormField key={name} control={form.control} name={`reminderOffsets.${name}`} render={({ field }) => <FormItem><FormLabel>{name.replace(/([A-Z])/g, " $1")}</FormLabel><FormControl><Input type="number" min={0} {...field} onChange={(e) => field.onChange(Number(e.target.value))} data-testid={`input-${name}`} /></FormControl><FormMessage /></FormItem>} />)}<FormField control={form.control} name="reminderOffsets.agentRenewalReminderDays" render={({ field }) => <FormItem><FormLabel>Agent renewal reminder days</FormLabel><FormControl><Input value={field.value.join(", ")} onChange={(e) => field.onChange(e.target.value.split(",").map(Number).filter(Number.isFinite))} data-testid="input-agent-reminder-days" /></FormControl><FormMessage /></FormItem>} /></CardContent></Card>
    <Card><CardHeader><CardTitle>Policy text sections</CardTitle><CardDescription>Edit the public legal policy sections. Counsel-review status is preserved.</CardDescription></CardHeader><CardContent className="space-y-6">{form.watch("policySections").map((section, i) => <div key={section.key} className="space-y-3 rounded border p-4"><FormField control={form.control} name={`policySections.${i}.title`} render={({ field }) => <FormItem><FormLabel>Title — {section.key}</FormLabel><FormControl><Input {...field} data-testid={`input-policy-title-${section.key}`} /></FormControl><FormMessage /></FormItem>} /><FormField control={form.control} name={`policySections.${i}.body`} render={({ field }) => <FormItem><FormLabel>Policy text</FormLabel><FormControl><Textarea rows={9} {...field} data-testid={`input-policy-body-${section.key}`} /></FormControl><FormMessage /></FormItem>} />{section.pendingCounselReview && <p className="text-sm text-amber-700">Pending counsel review</p>}</div>)}</CardContent></Card>
    {save.error && <DmcaError error={save.error} />}<div className="flex justify-end"><Button type="submit" disabled={save.isPending} data-testid="button-save-dmca-settings"><Save className="mr-2 h-4 w-4" />Save settings</Button></div>
  </form></Form></DmcaPage>;
}